;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-semi&comma
        c-indent-line-or-region
        csharp-maybe-insert-codedoc
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        ess-indent-or-complete
        ess-insert-assign
        ess-smart-S-assign
        ess-smart-comma
        ess-yank
        fill-paragraph
        forward-whitespace
        hydra--digit-argument
        hydra-multiple-cursors/nil
        ignore
        indent-for-tab-command
        indent-region
        kill-region
        markdown-outdent-or-delete
        phi-search
        sgml-slash
        swiper
        tab-to-tab-stop
        xah-math-input-change-to-symbol
        ))

(setq mc/cmds-to-run-once
      '(
        ess-eval-buffer
        eval-print-last-sexp
        find-file
        goto-line
        handle-switch-frame
        hydra-multiple-cursors/ignore-and-exit
        hydra-multiple-cursors/lambda-a
        hydra-multiple-cursors/lambda-b
        hydra-multiple-cursors/lambda-f
        hydra-multiple-cursors/lambda-i
        hydra-multiple-cursors/lambda-m
        hydra-multiple-cursors/lambda-n
        init--toggle-presentation-mode
        ivy-switch-buffer
        mark-whole-buffer
        mouse-set-region
        my-open-file-manager
        save-some-buffers
        swiper-all
        w32-drag-n-drop
        ))
